name = "SAP"
uuid = "402d3d34-36ff-4168-9320-77b8f6c9fa01"
authors = ["Ivan Melchor <ifmelchor@unrn.edu.ar> and contributors"]
version = "0.1.0"

[deps]
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Multitaper = "a81958ac-9ec9-4086-814d-3ae87249a5e8"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
BandPower = "Multitaper"
GPUzlcc = "CUDA"

[compat]
Contour = "0.6.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
